### PR TITLE
NET-450 (SLP-06) Improve seeker account signatures

### PR DESCRIPTION
**Pull request by JCSanPedro**
## Motivation

Currently we validate that seeker signatures are submitted within a `proofDuration` time frame. This is to prevent the signature from being reused at a later date. This approach is a remnant of when we were relying on an external Oracle to validate the Seeker proof. This is no longer necessary and we can now just store and use a nonce with each signature to ensure that each one is unique.

## Summary of Changes

- Replace `proofDuration` with a `nonce` in the signature message
- Track nonces in storage to prevent reuse

### CODE REVIEW

**Review by JoshD641 — DISMISSED** [review]
Good approach and good test coverage, LGTM.

**Review by teinnt — COMMENTED** [review]
Wow, this approach is cool 🚀🚀🚀 Btw, do we wanna update the deploy script and genesis config to too?

**Comment by JCSanPedro** [comment]
> Wow, this approach is cool 🚀🚀🚀 Btw, do we wanna update the deploy script and genesis config to too?

Good catch. Will do now.

**Review by teinnt — APPROVED** [review]
LGTM

**Pull request merged**
